name: Update dist

on:
  push:
    branches: [ main ]

jobs:
  check-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: install
        run: yarn

      - name: package
        run: yarn package
      
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "xrkffgg@vip.qq.com"
          git config --global user.name "xrkffgg"
          git pull
          git add -A
          git commit -m "🤖 auto: updated dist" || exit 0
          git push
