name: 🤖 test

on:
  issues:
    types: [labeled]

jobs:
  auto-invite:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'test'
    steps:
      - uses: actions/checkout@master
        
      - name: install
        run: yarn

      - name: node js
        run: node ./src/main.js
